[package]
name = "galerians"
version = "0.1.0"
authors = ["Mark Tolmacs <mark@lazycat.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
clap = "*"

[[bin]]
name = "galerians"
path = "src/main.rs"
